### ISSUE TITLE
`use_autoprompt` argument not working

### ISSUE THREAD

**Issue by stefanwebb** [exa-labs/exa-py#30]
When I run a search it doesn't appear like the API enables the prompt rewriting when I set `use_autoprompt=True`.

Compare:

```
result = exa.search_and_contents(
  "hottest AI startups",
  type="neural",
  use_autoprompt=True,
  num_results=10,
  text=True,
  highlights={
    "num_sentences": 10,
    "highlights_per_url": 10
  }
)

for r in result.results:
    print(r.id)

print('\n\n')

result = exa.search_and_contents(
  "Here is a leading AI startup in the industry:",
  type="neural",
  use_autoprompt=True,
  num_results=10,
  text=True,
  highlights={
    "num_sentences": 10,
    "highlights_per_url": 10
  }
)
```

**Comment by Feel-ix-343** [comment]
Hello!

I believe this is working now.

Search results for: 'hottest AI startups'
https://www.paradox.ai/
https://www.harvey.ai/
https://11x.ai/
https://brain.ai/#/
https://www.adept.ai/
https://directai.io/?utm_source=twitter&utm_medium=raw_message&utm_campaign=first_launch
https://www.tenyx.com/
https://rain.ai/
https://www.helm.ai/
https://www.useghost.ai/


Search results for: 'Here is a leading AI startup in the industry:'
https://cognino.ai/
https://www.pyqai.com/
https://www.arya.ai/
https://www.gnani.ai/
https://humaan.ai/
https://haltia.ai/
https://11x.ai/
https://www.useghost.ai/
https://www.tenyx.com/
https://www.aiah.ai/

and with autoprompt set to false

Search results for: 'hottest AI startups'
https://www.nfx.com/post/generative-ai-hot-75-list
https://www.businessinsider.com/the-most-promising-artificial-intelligence-startups-of-2023-2023-8?op=1
https://www.axios.com/2023/09/19/ai-security-startup-market
https://www.ai-startups.org/
https://techcrunch.com/2023/09/06/5-neat-ai-startups-from-y-combinators-winter-2023-batch/
https://www.techmeme.com/230314/p32
https://news.crunchbase.com/ai/new-ai-unicorns-2023-list-llm-platforms-cohere/?utm_source=twitter&utm_medium=website&utm_campaign=SocialSnap
https://www.cbinsights.com/research/artificial-intelligence-top-startups-2023/
https://www.aitoprank.com/
https://twitter.com/NFX/status/1651621295107502081


Search results for: 'Here is a leading AI startup in the industry:'
https://norn.ai/
https://cognino.ai/
https://www.pyqai.com/
https://www.gnani.ai/
https://www.arya.ai/
https://www.useghost.ai/
https://haltia.ai/
https://11x.ai/
https://saarthi.ai/
https://www.adept.ai/
