### ISSUE TITLE
Keyword search fails when include_domains is specified.

### ISSUE THREAD

**Issue by maralski** [exa-labs/exa-py#6]
Keyword search fails when include_domains is defined.

This snippet fails with:

> Exception: Request failed with status code 500. Message: {"error":"An error occurred during the keyword search"}

```
response = metaphor.search(
    "These are my keywords",
    type="keyword",
    include_domains=["x.com"]
)
```

Removing `include_domains=["x.com"]` succeeds

**Comment by jeffzwang** [comment]
Huh...lemme look into this @maralski !

**Comment by jeffzwang** [comment]
@maralski I can't seem to replicate this. mind sharing which version of our SDK you're using?

**Comment by maralski** [comment]
If I use type="neutral" it works ok.

```
metaphor-python==0.1.16
```

**Comment by jeffzwang** [comment]
It will fail if there are multiple domains you put there, because we can't support that

**Comment by maralski** [comment]
Confirmed keyword search works with 1 domain

**Comment by Feel-ix-343** [comment]
Hello!

reopen this if the issue is still occuring; for now, I am closing
